apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mcsv-eureka
  name: mcsv-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mcsv-eureka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/service3it-network: "true"
        io.kompose.service: mcsv-eureka
    spec:
      containers:
        - image: service3it-eureka:latest
          name: mcsv-eureka
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
