spring:
    application:
        name: mcsv-auth
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuerUri: ${AWS_CONGNITO_IDP_URL}
                    jwkSetUri: ${AWS_COGNITO_IDP_JWKS_URL}

server:
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        registerWithEureka: true
        fetchRegistry: true
    instance:
        instance-id: ${spring.application.name}:${server.port}
        hostname: ${spring.application.name}