apiVersion: v1
kind: Secret
metadata:
  name: datasource-secret
type: Opaque
data:
  MYSQL_DATABASE: c2VydmljZTNpdC1kYXRh #service3it-data
  MYSQL_USER: c2VydmljZTNpdA== #service3it
  MYSQL_PASSWORD: c2VydmljZTNpdA== #service3it
  MYSQL_ROOT_PASSWORD: c2VydmljZTNpdA== #service3it